# Generated by Django 5.1.1 on 2024-09-30 11:59

import ckeditor_uploader.fields
import colorfield.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('name', models.CharField(max_length=256, verbose_name='Ismi')),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('regex=r^\\d{9}$', message='wrong_phone_format')], verbose_name='Telefon raqami')),
                ('file', models.FileField(upload_to='file/%Y%m', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])], verbose_name='Rezyume')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('file', models.FileField(upload_to='awards%Y%m', validators=[django.core.validators.FileExtensionValidator(['png', 'svg', 'jpg', 'jpeg'])], verbose_name='Sertificat')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('url', models.CharField(max_length=256, verbose_name='Havol')),
            ],
            options={
                'verbose_name': 'Xalqaro mukofot va sertifikat',
                'verbose_name_plural': 'Xalqaro mukofat va sertifikatlar',
                'db_table': 'awards',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=256, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=256, verbose_name='Slug')),
                ('cover', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[200, 195], upload_to='blog%Y%M', verbose_name='Rasm')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[890, 480], upload_to='blog%Y%m', verbose_name='rasm')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Kontent')),
                ('published_at', models.DateField(default=django.utils.timezone.now, verbose_name='Nashr qilingan sana')),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog Postlar',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='CeoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('full_name', models.CharField(max_length=256, verbose_name='Toliq_ism')),
                ('position', models.CharField(max_length=256, verbose_name='Lavozim')),
                ('image', models.ImageField(upload_to='ceoreview/', verbose_name='Rasmi')),
                ('signature', models.ImageField(upload_to='ceo/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['png', 'svg', 'jpg', 'jpeg'])], verbose_name='imzo')),
                ('comment', models.TextField(verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Kompaniya egasi tavsiya',
                'verbose_name_plural': 'Kompaniya egasi tavsifi',
                'db_table': 'ceo_review',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('full_name', models.CharField(max_length=256, verbose_name='Ism familiya')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('message', models.TextField(verbose_name='message')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=256, verbose_name='ism/Nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('phone', models.CharField(max_length=256, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('twitter', models.CharField(max_length=256, verbose_name='Twitter havolasi')),
                ('facebook', models.CharField(max_length=256, verbose_name='Facebook havolasi')),
                ('telegram', models.CharField(max_length=256, verbose_name='Telegram havolasi')),
                ('instagram', models.CharField(max_length=256, verbose_name='instgram havolasi')),
            ],
            options={
                'verbose_name': "Kontakt ma'lumot",
                'verbose_name_plural': "Kontakt ma'lumotlari",
                'db_table': 'contact_details',
            },
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=256, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'db_table': 'departament',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=256, verbose_name='Nomi')),
                ('location', models.CharField(max_length=256, verbose_name='Joylashuvi')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Kontent')),
                ('date', models.DateTimeField(verbose_name='Sanasi')),
            ],
            options={
                'verbose_name': 'Munim voqea',
                'verbose_name_plural': 'Muhim voqealar',
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('question', models.TextField(verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'F.A.Q',
                'verbose_name_plural': 'F.A.Q',
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='Flavours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('product', models.CharField(max_length=256, verbose_name='Mahsulot nomi')),
                ('flavour', models.CharField(max_length=256, verbose_name="Ta'mlari")),
                ('order', models.SmallIntegerField(default=0, verbose_name='Tartibi')),
            ],
            options={
                'verbose_name': "Ta'm",
                'verbose_name_plural': "Ta'mlar",
                'db_table': 'flavours',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=256, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=256, verbose_name='Slug')),
                ('cover', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[200, 195], upload_to='news%Y%M', verbose_name='Rasm')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[890, 480], upload_to='news%Y%m', verbose_name='rasm')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Kontent')),
                ('published_at', models.DateField(default=django.utils.timezone.now, verbose_name='Nashr qilingan sana')),
            ],
            options={
                'verbose_name': 'news post',
                'verbose_name_plural': 'news Postlar',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('file', models.FileField(upload_to='partners/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['png', 'svg', 'jpg', 'jpeg'])], verbose_name='logo')),
                ('order', models.IntegerField(default=8, verbose_name='Tartibi')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=256, verbose_name='Nomi')),
                ('description', models.TextField(max_length=256, verbose_name='Tavsif')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Rangi')),
                ('hover', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='hover')),
                ('image_center', models.ImageField(upload_to='product/%Y%m', verbose_name='Asosiy rasm')),
                ('image_left', models.ImageField(upload_to='product/%y/%m', verbose_name='Birinchi rasm')),
                ('image_right', models.ImageField(upload_to='product/top/%Y%m', verbose_name='Ikkinchi rasm')),
            ],
            options={
                'verbose_name': 'Asosiy mahsulot',
                'verbose_name_plural': 'Asosiy mahsulotlar',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('description', models.TextField(max_length=256, verbose_name='Tavsif')),
                ('video', models.CharField(max_length=256, verbose_name='Video links')),
                ('sold', models.BigIntegerField(verbose_name='Sotilgan mahsulotlar soni')),
                ('sold_year', models.DateField(verbose_name='Sotilgan yil')),
                ('stores', models.IntegerField(verbose_name='Rastalar soni')),
                ('team', models.IntegerField(verbose_name="Jamoa a'zolari soni")),
                ('established_year', models.DateField(verbose_name='Asos solinga yil')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistika',
                'db_table': 'statistics',
            },
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('tweet', models.TextField(verbose_name='Twit')),
                ('url', models.CharField(max_length=256, verbose_name='Havola')),
            ],
            options={
                'verbose_name': 'twitter',
                'verbose_name_plural': 'Twitter',
                'db_table': 'twitter',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=256, verbose_name='Nomi')),
                ('salary', models.IntegerField(default=8, verbose_name='Maosh')),
                ('salary_type', models.IntegerField(choices=[(1, 'Belgilanga'), (2, 'Kelishiladi')], default=1, verbose_name='Maosh turi')),
                ('location', models.CharField(max_length=256, verbose_name='Joylashuv')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Kontent')),
                ('from_day', models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba'), (7, 'Yakshanba')], default=1, verbose_name='Ish boshlanish kuni')),
                ('to_day', models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba'), (7, 'Yakshanba')], default=6, verbose_name='ish tugash kuni')),
                ('from_time', models.TimeField(verbose_name='ish boshlanish vaqti')),
                ('job_type', models.IntegerField(choices=[(1, "To'liq stavka"), (2, 'Yarim stavka')], default=1, verbose_name='ish turi')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='common.departament', verbose_name="Bo'lim")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=256, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('price', models.IntegerField(verbose_name='Naxi')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Rangi')),
                ('hover', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='hover')),
                ('image_main', models.ImageField(upload_to='product/%Y%m', verbose_name='Asosiy rasm')),
                ('image_first', models.ImageField(upload_to='product/%Y%m', verbose_name='Birinchi rasm')),
                ('image_second', models.ImageField(upload_to='product/%y/%m', verbose_name='Ikkinchi rasm')),
                ('image_third', models.ImageField(upload_to='product/top/%Y%m', verbose_name='Uchinchi rasm')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('facts', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Faktlar')),
                ('buy_now_link', models.CharField(blank=True, max_length=256, verbose_name='Faktlar')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='common.product', verbose_name='Mahuslot04')),
            ],
            options={
                'verbose_name': 'Mahsulot turi',
                'verbose_name_plural': 'Mahsulot turlari',
                'db_table': 'product_types',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=256, verbose_name='Nomi')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Tavsif')),
                ('file', models.FileField(upload_to='ingredients/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='icon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inggredients', to='common.producttypes', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'ingredients',
                'verbose_name_plural': 'ingredients',
                'db_table': 'ingredients',
            },
        ),
    ]
