# Generated by Django 5.0.6 on 2024-10-15 11:34

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=50, verbose_name='nomi')),
                ('slug', models.SlugField(max_length=256, verbose_name='Slug')),
                ('cover', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[200, 195], upload_to='blog%Y%M', verbose_name='Rasm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
